sudo: required
language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - python-pip
      - python-dev

services:
  - docker

before_install:
  - pip install tox detox

jobs:
  include:
    - stage: Messaging Abstraction module unit tests
      script:
        - detox
